# Uncomment this line to define a global platform for your project

target 'Playbasis' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  platform :ios, '8.0'

  # Pods for Playbasis
  pod 'OCMapper', :path => "CustomPodspecs/OCMapper/OCMapper.podspec"

end

target 'PlaybasisMacOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  platform :osx, '10.8'

  # Pods for PlaybasisMacOS
  pod 'OCMapper', :path => "CustomPodspecs/OCMapper/OCMapper.podspec"

end
